services:
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.12-management-alpine
    ports:
      - 15672:15672

  celery:
    image: celery:latest
    build:
      context: celery/
    deploy:
      resources:
        limits:
          cpus: '12.0'
        reservations:
          cpus: '12.0'
